### ISSUE TITLE
provided example does not work

### ISSUE THREAD

**Issue by niron1** [temyers/serverless-localstack#32] opened 2018-04-03 13:51 UTC
Hi,
I have a localstack stack up and running. I'm trying to upload the provided example:
```
~/code/serverless-localstack/example/service$ serverless deploy --verbose --stage local
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Using serverless-localstack-plugin
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Attribute without value
Line: 17
Column: 70
Char: a
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.9.0
     Serverless Version:     1.26.0

```

**Comment by actsasgeek** [comment] 2018-05-01 18:06
```
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..
Serverless: Stack update finished...

  Serverless Error ---------------------------------------

  Attribute without value
Line: 13
Column: 70
Char: a

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.0.0
     Serverless Version:     1.26.1
```
Same error although a different line number. I have no idea _what_ to fix.

**Comment by bargenson** [comment] 2018-05-05 00:09
Same thing here on a project I'm working on...
`
Serverless Error ---------------------------------------
 
  ServerlessError: Attribute without value
Line: 17
Column: 70
Char: a
 
  Stack Trace --------------------------------------------
 
ServerlessError: ServerlessError: Attribute without value
Line: 17
Column: 70
Char: a
    at AwsDeploy.BbPromise.bind.then.catch (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:87:15)
From previous event:
    at AwsDeploy.createStack (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:76:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/plugins/aws/deploy/index.js:108:10)
    at BbPromise.reduce (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/bargenson/Development/mylittleday/akegecko/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.6.0
     Serverless Version:     1.26.1
`

Seems to be related

**Comment by bargenson** [comment] 2018-05-05 00:31
It seems to be caused by an XML parsing error of the following answer from CloudFormation :
```
<DescribeStacksResponse>
  <DescribeStacksResult>
    <Stacks>
      <member>
        <StackName>akegecko-local</StackName>
        <StackId>arn:aws:cloudformation:us-east-1:123456789:stack/akegecko-local/3a9647ad-ad9f-42e7-87f2-b56a2a211222</StackId>
        <CreationTime>2010-07-27T22:28:28Z</CreationTime>
        <StackStatus>UPDATE_COMPLETE</StackStatus>
        <NotificationARNs/>
        <DisableRollback>false</DisableRollback>
        <Outputs>
          <member>
            <OutputKey>ServerlessDeploymentBucketName</OutputKey>
            <OutputValue>akegecko-local-ServerlessDeploymentBucket-595732825350</OutputValue>
          </member>
          <member>
            <OutputKey>ImportAkeneoProductsChangesLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fd87bf50></OutputValue>
          </member>
          <member>
            <OutputKey>CreateOrUpdateAkeneoProductLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fdaa2850></OutputValue>
          </member>
          <member>
            <OutputKey>ConvertObjectAndSendToTopicLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fda98750></OutputValue>
          </member>
          <member>
            <OutputKey>ImportRentashopCategoriesLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fd87b710></OutputValue>
          </member>
          <member>
            <OutputKey>AddImageToProductLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fd85ac50></OutputValue>
          </member>
          <member>
            <OutputKey>ImportRentashopProductsLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fdaa2ed0></OutputValue>
          </member>
          <member>
            <OutputKey>CreateOrUpdateAkeneoCategoryLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fd87b450></OutputValue>
          </member>
          <member>
            <OutputKey>CreateOrUpdateTradegeckoProductLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f68fda984d0></OutputValue>
          </member>
          <member>
            <OutputKey>ServiceEndpoint</OutputKey>
            <OutputValue>https://<moto.apigateway.models.RestAPI object at 0x7f68fd85a490>.execute-api.us-east-1.amazonaws.com/local</OutputValue>
          </member>
        </Outputs>
        <Parameters>
        </Parameters>
        <Tags>
            <member>
              <Key>STAGE</Key>
              <Value>local</Value>
            </member>
        </Tags>
      </member>
    </Stacks>
  </DescribeStacksResult>
</DescribeStacksResponse>
```
The problem is the `<moto.awslambda.models.LambdaVersion object 
at 0x7f68fd87bf50>` that seems to not be correctly serialized by localstack.

**Comment by bargenson** [comment] 2018-05-05 00:35
The error seems to come from there : https://github.com/spulec/moto/issues/1588

**Comment by justinm** [comment] 2018-09-17 23:14
PR https://github.com/temyers/serverless-localstack/pull/37 has been merged. Please reopen if this is still an issue.

**Closed by justinm** 2018-09-17 23:14 UTC
Labels: bug
