### ISSUE TITLE
deploy fails with socket hang up

### ISSUE THREAD

**Issue by yohei1126** [temyers/serverless-localstack#10] opened 2017-07-06 14:31 UTC
I got the following error when I run `serverless deploy`.

* Node 8.1.2
* serverless 1.17.0
* localstack 0.6.0
* serverless-localstack 0.0.2

```
root@33e68990f0b3:/app/example/service# serverless deploy
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service apigateway to use http://localstack:4567
Serverless: Reconfiguring service cloudformation to use http://localstack:4581
Serverless: Reconfiguring service cloudwatch to use http://localstack:4582
Serverless: Reconfiguring service lambda to use http://localstack:4574
Serverless: Reconfiguring service dynamodb to use http://localstack:4567
Serverless: Reconfiguring service s3 to use http://localstack:4572
Serverless: Reconfiguring service ses to use http://localstack:4579
Serverless: Reconfiguring service sns to use http://localstack:4575
Serverless: Reconfiguring service sqs to use http://localstack:4576
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
..
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (2.06 KB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
  socket hang up
 
  Get Support --------------------------------------------
```

This is my serverless.yml.

```serverless.yml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-plugin-localstack

custom:
  localstack:
    host: http://localstack
    debug: true

functions:
  hello:
    handler: handler.hello
    events:
      - sns: ${env:EXISTING_TOPIC_ARN}
```

**Comment by justinm** [comment] 2017-07-10 15:08
socket hang up errors are typically caused by exceptions being thrown from LocalStack. Providing the LocalStack logs will be helpful in diagnosing this issue.

**Comment by yohei1126** [comment] 2017-07-11 11:00
```
ERROR:localstack.services.generic_proxy:Error forwarding request: list index out of range
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 144, in forward
data=data, headers=forward_headers, response=response)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 150, in update_cloudformation
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 444, in deploy_template
resource['__details__'] = stack_resources[0]
IndexError: list index out of range
ERROR:localstack.services.generic_proxy:Error forwarding request: list index out of range
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 144, in forward
data=data, headers=forward_headers, response=response)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 150, in update_cloudformation
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 444, in deploy_template
resource['__details__'] = stack_resources[0]
IndexError: list index out of range
ERROR:localstack.services.generic_proxy:Error forwarding request: list index out of range
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 144, in forward
data=data, headers=forward_headers, response=response)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 150, in update_cloudformation
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 444, in deploy_template
resource['__details__'] = stack_resources[0]
IndexError: list index out of range
ERROR:localstack.services.generic_proxy:Error forwarding request: list index out of range
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 144, in forward
data=data, headers=forward_headers, response=response)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 150, in update_cloudformation
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 444, in deploy_template
resource['__details__'] = stack_resources[0]
IndexError: list index out of range
```

**Comment by rlgod** [comment] 2017-09-14 22:12
I'm getting exactly the same issue and stack output. Any ideas what could be causing this?

**Comment by sabrehagen** [comment] 2017-10-02 06:53
Me too, did anyone solve this?

**Comment by gitis** [comment] 2017-12-28 09:58
I am getting the same error when creating the stack with a command
`aws cloudformation create-stack --stack-name test-stack --template-body=file:///cloudformation-mnt/templates/localstack.template --endpoint http://localstack:4581`

`
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 196, in forward
  updated_response = self.proxy.update_listener.return_response(**kwargs)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 183, in return_response
  template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 485, in deploy_template
  resource['__details__'] = stack_resources[0]
`

**Comment by temyers** [comment] 2018-01-10 00:17
Closing as this is an upstream issue

**Closed by temyers** 2018-01-10 00:17 UTC
Labels: upstream

**Comment by sabrehagen** [comment] 2018-01-10 00:50
Can you link the upstream issue please?

**Comment by temyers** [comment] 2018-01-10 02:29
I haven't created a specific upstream issue.  

If you're still experiencing issues, I suggest you raise it with localstack: https://github.com/localstack/localstack/issues
