### ISSUE TITLE
not being able to deploy fully

### ISSUE THREAD

**Issue by niron1** [temyers/serverless-localstack#30] opened 2018-04-02 12:54 UTC
Hi I get the following, any help will be greatly appreciated, thanks.
 
 serverless deploy --verbose --stage local
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4567
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
 
  Serverless Error ---------------------------------------
 
  **ServerlessError: Attribute without value
Line: 17
Column: 70
Char: a**
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.9.0
     Serverless Version:     1.26.1

**Comment by justinm** [comment] 2018-09-09 06:52
This issue is likely caused by #38 or #24. Closing as a duplicate.

**Closed by justinm** 2018-09-09 06:52 UTC
Labels: duplicate
