### ISSUE TITLE
Attribute without value

### ISSUE THREAD

**Issue by juancho088** [temyers/serverless-localstack#27] opened 2018-03-15 08:26 UTC
At the end of my infrastructure creation I'm having this issue:

```
  Serverless Error ---------------------------------------

  Attribute without value
Line: 13
Column: 70
Char: a

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.1
     Serverless Version:     1.25.0
```

I was checking the plugin code, but I didn't find anything weird. There is no bug from Localstack side and this error is blocking the API Gateway creation. Please help

**Comment by temyers** [comment] 2018-03-17 02:03
Is there any more detail if you enable debug mode:

`export SLS_DEBUG=*`

Can you create an [example](https://stackoverflow.com/help/mcve), as a failing test and submit as a PR?

**Comment by temyers** [comment] 2018-03-17 02:09
duplicate of #24

**Closed by temyers** 2018-03-17 02:09 UTC
